# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativebaseKitchenSink' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativebaseKitchenSink
  pod 'AppCenter/Crashes', '~> 1.6.0'
  pod 'AppCenter/Analytics', '~> 1.6.0'
  pod 'AppCenterReactNativeShared', '~> 1.5.0'

  

  platform :ios, '9.0'
  target 'NativebaseKitchenSinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NativebaseKitchenSink-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativebaseKitchenSink-tvOS

  target 'NativebaseKitchenSink-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
